name: goodman_pipeline
channels:
  - astroconda
dependencies:
  - numpy
  - pandas==0.23.0
  - matplotlib
  - scipy==1.3.1
  - cython
  - astropy
  - pip
  - pip:
    - ccdproc
    - coveralls
    - astroplan
    - mock
    - sphinx
    - sphinxcontrib.napoleon
